# Vessel Configuration

# Available access types:
# - all: Any user can perform this action
# - mod: Room founder, mods and admins can perform this action
# - mod: Mods and admins can perform this action
# - admin: Only admins can perform this action
# - none: Action is not allowed (superadmins bypass this)

# Default rooms
main_channel_name: "Main"
shout_channel_name: "Shouts"

# Room creation
allow_room_creation: true # Turning this off will completely disable room creation
room_creation_public: "mod" # Rooms that are visible to all clients and can be joined by name
room_creation_unlisted: "all" # Rooms that are invisible but can be joined by UUID

room_deletion: "founder" # Permission required to delete rooms
room_modify_userdata: "founder" # Permission required to modify room userdata

# Listing
list_online_users: "all" # Permission level required to get a list of online users

# Welcome message
welcome_message:
  - "Welcome to Vessel!"
  - "Type /public to see a list of public rooms."
  - "You can also join public or unlisted rooms with /join."

# Persistence
database: "sqlite://data.db" # Leave as an empty string to use the DATABASE environment variable.
# If both this^ and the DATABASE environment variable are blank, or the database is set to "sqlite://:memory:", persistence will be disabled.
# Vessel uses Sequelize, so database must be a Sequelize-compatible URL.
# 
# For example:
# sqlite://data.db - "data.db" file in Vessel's installlation folder
# postgres://user:pass@example.com:5432/dbname - dbname on example.com, logging in with user "user" and password "pass"
# 
# Note: You will need to install certain additional drivers for some databases.
# See https://sequelize.org/docs/v6/getting-started/ for more information.
# The sqlite3 driver is installed with Vessel, so don't worry about installing that.


# Other
mod_key: "" # Leave as an empty string to use the MODKEY environment variable
admin_key: "" # Leave as an empty string to use the ADMINKEY environment variable

# WARNING: Superadmins have complete control over user/room tables and can easily damage the server.
# Don't give out superadmin to anyone you don't COMPLETELY trust!
superadmin_key: "" # Leave as an empty string to use the SUPERADMINKEY environment variable

port: 8692
